version: '2.3'
services:
  redis-server:
    restart: always
    image: redis:alphine
    container_name: redis-server-auth
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6380:6379"
    volumes:
      - ./redis:/data